spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitbit_agent
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
logging:
  level: 
    com.fitbitagent: DEBUG