spring:
  application:
    name: fitbit-agent

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.fitbitagent.domain
  configuration:
    map-underscore-to-camel-case: true
